---
x-env-files: &ros2-develop-env-files
  - env_files/rust.env
  - env_files/ignition_gazebo.env
  - env_files/ros2.env
  - env_files/xwindow.env

x-ros2-shared-volumes: &ros2-shared-volumes
  - type: bind
    source: /var/run/udev
    target: /var/run/udev
  - type: bind
    source: /tmp
    target: /tmp
  - type: bind
    source: /dev
    target: /dev
  - type: bind
    source: ./rmw_profiles/rmw_cyclonedds_profile.xml
    target: /rose/colcon_ws/profiles/rmw_cyclonedds_profile.xml
    read_only: true
  - type: bind
    source: ./rmw_profiles/rmw_fastrtps_profile.xml
    target: /rose/colcon_ws/profiles/rmw_fastrtps_profile.xml
    read_only: true

services:
  xwindow:
    image: busybox
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
      - type: bind
        source: ~/.Xauthority
        target: /root/.Xauthority
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
  jazzy-workspace:
    image: busybox
    profiles:
      - jazzy
    volumes:
      - type: bind
        source: ./workspace/jazzy/src
        target: /rose/colcon_ws/src
      - type: bind
        source: ./workspace/jazzy/build
        target: /rose/colcon_ws/build
      - type: bind
        source: ./workspace/jazzy/install
        target: /rose/colcon_ws/install
  humble-workspace:
    image: busybox
    profiles:
      - humble
    volumes:
      - type: bind
        source: ./workspace/humble/src
        target: /rose/colcon_ws/src
      - type: bind
        source: ./workspace/humble/build
        target: /rose/colcon_ws/build
      - type: bind
        source: ./workspace/humble/install
        target: /rose/colcon_ws/install
  developer-local-config:
    image: busybox
    volumes:
      - type: bind
        source: ~/.vim
        target: /root/.vim
        read_only: true
      - type: bind
        source: ~/.vimrc
        target: /root/.vimrc
        read_only: true
      - type: bind
        source: ~/.inputrc
        target: /root/.inputrc
        read_only: true
  jazzy-runtime:
    build:
      context: docker
      args:
        ROS_DISTRO: jazzy
        BASE_IMAGE: ubuntu:24.04
        GZ_VERSION: harmonic
      target: rose-runtime
    image: naokitakahashi12/rose:jazzy-runtime
    profiles:
      - jazzy
    shm_size: 256m
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes: *ros2-shared-volumes
    env_file:
      - env_files/ros2.env
    environment:
      - ROS_HOSTNAME=jazzy-runtime
    command: iox-roudi
  jazzy:
    build:
      context: docker
      args:
        ROS_DISTRO: jazzy
        BASE_IMAGE: ubuntu:24.04
        GZ_VERSION: harmonic
      target: rose-develop
    image: naokitakahashi12/rose:jazzy-develop
    profiles:
      - jazzy
    shm_size: 256m
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/dri
    volumes_from:
      - xwindow
      - jazzy-workspace
      - developer-local-config
    volumes: *ros2-shared-volumes
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=jazzy
    command: >
      /bin/bash
  humble-runtime:
    build:
      context: docker
      args:
        ROS_DISTRO: humble
        BASE_IMAGE: ubuntu:22.04
      target: rose-runtime
    image: naokitakahashi12/rose:humble-runtime
    profiles:
      - humble
    shm_size: 256m
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes: *ros2-shared-volumes
    env_file:
      - env_files/ros2.env
    environment:
      - ROS_HOSTNAME=humble-runtime
    command: iox-roudi
  humble:
    build:
      context: docker
      args:
        ROS_DISTRO: humble
        IGNITION_VERSION: garden
        BASE_IMAGE: ubuntu:22.04
      target: rose-develop
    image: naokitakahashi12/rose:humble-develop
    profiles:
      - humble
    shm_size: 256m
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/dri
    volumes_from:
      - xwindow
      - humble-workspace
      - developer-local-config
    volumes: *ros2-shared-volumes
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=humble
    command: >
      /bin/bash
  humble-foxglove-bridge:
    image: naokitakahashi12/rose:humble-develop
    profiles:
      - humble
    volumes: *ros2-shared-volumes
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=humble-foxglove-bridge
    command: >
      ros2 run foxglove_bridge foxglove_bridge
