---
x-env-files: &ros2-develop-env-files
  - env_files/rust.env
  - env_files/ignition_gazebo.env
  - env_files/ros2.env
  - env_files/xwindow.env

x-rmw-profile-files: &ros2-rmw-profile-files
  - ./rmw_profiles/rmw_fastrtps_profile.xml:/rmw_fastrtps_profile.xml:ro
  - ./rmw_profiles/rmw_cyclonedds_profile.xml:/rmw_cyclonedds_profile.xml:ro

services:
  xwindow:
    image: busybox
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.docker.$USER.xauth:/tmp/.docker.xauth:ro
      - /etc/localtime:/etc/localtime:ro
  humble-workspace:
    image: busybox
    profiles:
      - humble
    volumes:
      - ./workspace/humble:/rose/colcon_ws:rw
  galactic-workspace:
    image: busybox
    profiles:
      - galactic
    volumes:
      - ./workspace/galactic:/rose/colcon_ws:rw
  developer-local-config:
    image: busybox
    volumes:
      - ~/.vim:/root/.vim:ro
      - ~/.vimrc:/root/.vimrc:ro
      - ~/.inputrc:/root/.inputrc:ro
  host-devices:
    image: busybox
    privileged: true
    volumes:
      - /var/run/udev
  humble-runtime:
    build:
      context: ros2
      args:
        ROS_DISTRO: humble
        BASE_IMAGE: ubuntu:22.04
      target: runtime
    image: naokitakahashi12/rose:humble-runtime
    profiles:
      - humble
    tty: true
    privileged: true
    volumes_from:
      - host-devices
    env_file:
      - env_files/ros2.env
    environment:
      - ROS_HOSTNAME=humble-runtime
    volumes: *ros2-rmw-profile-files
    command: >
      /bin/bash
  humble:
    build:
      context: ros2
      args:
        ROS_DISTRO: humble
        IGNITION_VERSION: garden
        BASE_IMAGE: ubuntu:22.04
      target: develop
    image: naokitakahashi12/rose:humble-develop
    profiles:
      - humble
    tty: true
    privileged: true
    shm_size: 256m
    devices:
      - /dev/dri
    volumes_from:
      - xwindow
      - humble-workspace
      - developer-local-config
      - host-devices
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=humble
    volumes: *ros2-rmw-profile-files
    working_dir: /rose/colcon_ws
    command: >
      /bin/bash
  humble-foxglove-bridge:
    build:
      context: ros2
      args:
        ROS_DISTRO: humble
        BASE_IMAGE: ubuntu:22.04
      target: runtime
    image: naokitakahashi12/rose:humble-runtime
    profiles:
      - humble
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=humble-foxglove-bridge
    volumes: *ros2-rmw-profile-files
    command: >
      ros2 run foxglove_bridge foxglove_bridge
  galactic-runtime:
    build:
      context: ros2
      args:
        ROS_DISTRO: galactic
        BASE_IMAGE: ubuntu:20.04
      target: runtime
    image: naokitakahashi12/rose:galactic-runtime
    profiles:
      - galactic
    tty: true
    volumes_from:
      - host-devices
    env_file:
      - env_files/ros2.env
    environment:
      - ROS_HOSTNAME=galactic-runtime
    volumes: *ros2-rmw-profile-files
    command: >
      /bin/bash
  galactic:
    build:
      context: ros2
      args:
        ROS_DISTRO: galactic
        IGNITION_VERSION: fortress
        BASE_IMAGE: ubuntu:20.04
      target: develop
    image: naokitakahashi12/rose:galactic-develop
    profiles:
      - galactic
    tty: true
    privileged: true
    shm_size: 256m
    devices:
      - /dev/dri
    volumes_from:
      - xwindow
      - galactic-workspace
      - developer-local-config
      - host-devices
    env_file: *ros2-develop-env-files
    environment:
      - ROS_HOSTNAME=galactic
    volumes: *ros2-rmw-profile-files
    working_dir: /rose/colcon_ws
    command: >
      /bin/bash
