repositories:
  micro_ros/micro_ros_agent:
    type: git
    url: https://github.com/micro-ROS/micro-ROS-Agent.git
    version: humble
  micro_ros/micro_ros_setup:
    type: git
    url: https://github.com/micro-ROS/micro_ros_setup.git
    version: humble
  moveit/moveit_task_constructor:
    type: git
    url: https://github.com/moveit/moveit_task_constructor.git
    version: humble
  rsasaki0109/ndt_omp_ros2:
    type: git
    url: https://github.com/rsasaki0109/ndt_omp_ros2.git
    version: humble
  rsasaki0109/lidar_localization_ros2:
    type: git
    url: https://github.com/rsasaki0109/lidar_localization_ros2.git
    version: main
  rst_tu_dortmund/teb_local_planner:
    type: git
    url: https://github.com/rst-tu-dortmund/teb_local_planner.git
    version: 630a22e88dc9fd45be726a762edbb5b776bef231
  rst_tu_dortmund/costmap_converter:
    type: git
    url: https://github.com/rst-tu-dortmund/costmap_converter.git
    version: 9565858432664e9cfe0b3556e1809336c4ab06d4
