repositories:
  gazebosim/ros_gz:
    type: git
    url: https://github.com/gazebosim/ros_gz.git
    version: jazzy
  ros_controls/gz_ros2_control:
    type: git
    url: https://github.com/ros-controls/gz_ros2_control.git
    version: jazzy
