#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import platform

import argparse
import subprocess

from shutil import which


class RoseCliHandler:
    def __init__(self):
        self.__init_arg_parser()
        self.__init_compose_command()

        try:
            import argcomplete
        except ImportError:
            pass
        else:
            argcomplete.autocomplete(self.arg_parser)

        self.parsed_args, self.parsed_unknown = self.arg_parser.parse_known_args()

        if hasattr(self.parsed_args, 'handler'):
            self.parsed_args.handler(self.parsed_args)
        else:
            self.arg_parser.print_help()

    def help(self, args):
        self.arg_parser.print_help()

    def version(self, args):
        # TODO
        print('rose version 0.0.0')

    def get_compose_prefix(self, args):
        print(' '.join(self.compose_command))

    def ps(self, args):
        execute_command = self.compose_command + ['ps']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def ls(self, args):
        execute_command = self.compose_command + ['ls']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def logs(self, args):
        execute_command = self.compose_command + ['logs']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def pull(self, args):
        execute_command = self.compose_command + ['pull']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def exec(self, args):
        execute_command = self.compose_command + ['exec']
        if args.args != '':
            execute_command = execute_command + [args.args]
        execute_command = execute_command + [args.service, 'bash']
        subprocess.run(execute_command)

    def start(self, args):
        execute_command = self.compose_command + ['start']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def stop(self, args):
        execute_command = self.compose_command + ['stop']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def up(self, args):
        if platform.system() == 'Linux':
            subprocess.run([
                'sh',
                os.path.join(
                    self.rose_package_dir,
                    'scripts',
                    'generate_docker_xauth.sh'
                )
            ])
        execute_command = self.compose_command + ['up', '-d']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)

    def down(self, args):
        execute_command = self.compose_command + ['down']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)
    
    def build(self, args):
        execute_command = self.compose_command + ['build']
        if args.args != '':
            execute_command = execute_command + [args.args]
        subprocess.run(execute_command)
    
    def __init_arg_parser(self):
        self.arg_parser = argparse.ArgumentParser(
            prog='rose',
            description='ROS Enviroment operation tools'
        )
        self.__init_sub_command()

    def __init_sub_command(self):
        self.sub_arg_parsers = self.arg_parser.add_subparsers(
            dest='subcommand',
            help='ROS Enviroment sub-commands'
        )

        common_parser_args = {
        }
        common_sub_cmd_args = {
            'nargs': '+',
            'action': 'append',
            'default': []
        }

        # TODO
        self.parsers = {}

        self.parsers['help'] = self.sub_arg_parsers.add_parser(
            'help',
            help='Show the ROSE help infomation.',
            **common_parser_args
        )
        self.parsers['help'].set_defaults(
            handler=self.help
        )
        self.parsers['version'] = self.sub_arg_parsers.add_parser(
            'version',
            help='Show the ROSE version infomation.',
            **common_parser_args
        )
        self.parsers['version'].set_defaults(
            handler=self.version
        )
        self.parsers['get_compose_prefix'] = self.sub_arg_parsers.add_parser(
            'get-compose-prefix',
            help='Get execute command prefix.',
            **common_parser_args
        )
        self.parsers['get_compose_prefix'].set_defaults(
            handler=self.get_compose_prefix
        )
        self.parsers['ps'] = self.sub_arg_parsers.add_parser(
            'ps',
            help='Show constainer process status.',
            **common_parser_args
        )
        self.parsers['ps'].set_defaults(
            handler=self.ps
        )
        self.parsers['ls'] = self.sub_arg_parsers.add_parser(
            'ls',
            help='List running compose containers.',
            **common_parser_args
        )
        self.parsers['ls'].set_defaults(
            handler=self.ls
        )
        self.parsers['logs'] = self.sub_arg_parsers.add_parser(
            'logs',
            help='View output log from container.',
            **common_parser_args
        )
        self.parsers['logs'].set_defaults(
            handler=self.logs
        )
        self.parsers['pull'] = self.sub_arg_parsers.add_parser(
            'pull',
            help='Pull ROSE service images.',
            **common_parser_args
        )
        self.parsers['pull'].set_defaults(
            handler=self.pull
        )
        self.parsers['exec'] = self.sub_arg_parsers.add_parser(
            'exec',
            help='Execute a bash command in a running container.',
            **common_parser_args
        )
        self.parsers['exec'].set_defaults(
            handler=self.exec
        )
        self.parsers['start'] = self.sub_arg_parsers.add_parser(
            'start',
            help='Start services.',
            **common_parser_args
        )
        self.parsers['start'].set_defaults(
            handler=self.start
        )
        self.parsers['stop'] = self.sub_arg_parsers.add_parser(
            'stop',
            help='Stop services.',
            **common_parser_args
        )
        self.parsers['stop'].set_defaults(
            handler=self.stop
        )
        self.parsers['up'] = self.sub_arg_parsers.add_parser(
            'up',
            help='Create and start services.',
            **common_parser_args
        )
        self.parsers['up'].set_defaults(
            handler=self.up
        )
        self.parsers['down'] = self.sub_arg_parsers.add_parser(
            'down',
            help='Stop and remove services.',
            **common_parser_args
        )
        self.parsers['down'].set_defaults(
            handler=self.down
        )
        self.parsers['build'] = self.sub_arg_parsers.add_parser(
            'build',
            help='Build or rebuild services.',
            **common_parser_args
        )
        self.parsers['build'].set_defaults(
            handler=self.build
        )

        self.parsers['exec'].add_argument(
            '-s',
            '--service',
            default='galactic'
        )

        for key, parser in self.parsers.items():
            parser.add_argument(
                '--args',
                help='Execute command argment string',
                default=''
            )

    def __set_this_directory_path(self):
        self.this_script_dir = os.path.dirname(os.path.realpath(__file__))

    def __init_compose_command(self):
        if which('docker') is None:
            raise OSError('Not found docker cil')
        try:
            subprocess.run(
                ['docker', 'compose', 'version'],
                stderr=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                check=True
            )
        except:
            print('Not found docker compose v2')
            print('Please install docker compose v2 https://docs.docker.com/compose/compose-v2/')
            sys.exit(1)

        self.__set_compose_command()

    def __set_compose_command(self):
        self.__set_this_directory_path()
        self.rose_package_dir = os.path.join(
            self.this_script_dir,
            '..'
        )

        self.compose_command = []
        self.compose_command.append('docker')
        self.compose_command.append('compose')

        self.compose_command += self.__gen_compose_file_path()

    def __gen_compose_file_path(self):
        compose_file_override = []

        compose_file_override.append('-f')
        compose_file_override.append(
            os.path.join(
                self.rose_package_dir,
                'docker-compose.yaml'
            )
        )

        if not which('nvidia-smi') is None:
            compose_file_override.append('-f')
            compose_file_override.append(
                os.path.join(
                    self.rose_package_dir,
                    'override',
                    'docker-compose.nvidia.yaml'
                )
            )

        return compose_file_override


if __name__ == '__main__':
    rose_cli_handler = RoseCliHandler()
