---
- hosts: all
  tasks:
    - name: Install compile toolchain packages
      block:
        - name: Install compile dependency from apt
          apt:
            install_recommends: false
            package:
              - gcc
              - g++
              - make
              - ninja-build
              - ccache
              - cmake
              - vim
              - mold
              - fzf
        - name: Install compile dependency from pip
          pip:
            name:
              - vcstool
              - rosdep
              - colcon-common-extensions
              - colcon-mixin
              - colcon-metadata
              - lark
              - numpy
              - tornado
              - simplejpeg
              - pillow
              - requests
              - empy==3.3.4
        - name: Install debug tools from apt
          apt:
            install_recommends: false
            package:
              - gdb
              - silversearcher-ag
        - name: Install colcon mixin
          shell: |
            colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        - name: Update colcon mixin
          shell: |
            colcon mixin update default
    - name: Install micro-ROS depencency packages
      apt:
        install_recommends: false
        package:
          - flex
          - bison
          - usbutils
          - libncurses-dev
          - libfastcdr-dev
    - name: Install ROSE develop command line tools
      apt:
        install_recommends: false
        package:
          - i2c-tools
    - name: Install ROSE develop ROS 2 packages
      block:
        - name: Get ROS 2 distro
          register: ros_distro
          shell: |
            if [[ $(echo {{ lookup("env", "ROS_DISTRO") }} | wc -c) -eq 0 ]]; then \
              exit 129; \
            fi
            echo {{ lookup("env", "ROS_DISTRO") }}
        - name: Install develop common packages
          when: ros_distro.stdout in ['humble', 'galactic', 'jazzy', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-ament-cmake
              - ros-{{ ros_distro.stdout }}-ament-cmake-vendor-package
              - ros-{{ ros_distro.stdout }}-generate-parameter-library
              - ros-{{ ros_distro.stdout }}-rviz2
        - name: Install SLAM and localization packages from apt
          when: ros_distro.stdout in ['humble', 'galactic', 'jazzy', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-cartographer-ros
              - ros-{{ ros_distro.stdout }}-gtsam
              - ros-{{ ros_distro.stdout }}-libg2o
        - name: Install navigation2 packages from apt
          when: ros_distro.stdout in ['humble', 'galactic', 'jazzy', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-rcl-interfaces
              - ros-{{ ros_distro.stdout }}-nav2-bringup
              - ros-{{ ros_distro.stdout }}-nav2-simple-commander
              - ros-{{ ros_distro.stdout }}-nav2-mppi-controller
        - name: Install tool optional packages
          when: ros_distro.stdout in ['humble', 'galactic', 'jazzy', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-pointcloud-to-laserscan
              - ros-{{ ros_distro.stdout }}-moveit-setup-assistant
              - ros-{{ ros_distro.stdout }}-rqt-image-view
              - ros-{{ ros_distro.stdout }}-rqt-plot
              - ros-{{ ros_distro.stdout }}-rqt-robot-monitor
              - ros-{{ ros_distro.stdout }}-rqt-runtime-monitor
              - ros-{{ ros_distro.stdout }}-rqt-service-caller
        - name: Install foxglove packages
          when: ros_distro.stdout in ['humble', 'galactic', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-foxglove-bridge
        - name: Install plotjuggler packages
          when: ros_distro.stdout in ['humble', 'galactic', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-plotjuggler
              - ros-{{ ros_distro.stdout }}-plotjuggler-ros
        - name: Install rviz2 plugins packages
          when: ros_distro.stdout in ['humble', 'galactic', 'jazzy', 'rolling']
          apt:
            install_recommends: false
            package:
              - ros-{{ ros_distro.stdout }}-rviz-default-plugins
              - ros-{{ ros_distro.stdout }}-rviz-imu-plugin
              - ros-{{ ros_distro.stdout }}-rviz-2d-overlay-plugins
              - ros-{{ ros_distro.stdout }}-nav2-rviz-plugins
              - ros-{{ ros_distro.stdout }}-octomap-rviz-plugins
              - ros-{{ ros_distro.stdout }}-grid-map-rviz-plugin
              - ros-{{ ros_distro.stdout }}-vision-msgs-rviz-plugins
              - ros-{{ ros_distro.stdout }}-polygon-rviz-plugins
