---
- hosts: all
  pre_tasks:
    - name: Resolve ROSE context
      import_tasks: ../tasks/resolve_rose_context.yaml
  tasks:
    - name: Update apt cache
      become: "{{ rose_use_become }}"
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base common packages
      become: "{{ rose_use_become }}"
      apt:
        install_recommends: false
        name:
          - ca-certificates
