---
- hosts: all
  pre_tasks:
    - name: Resolve ROSE context
      import_tasks: ../tasks/resolve_rose_context.yaml
      vars:
        rose_require_ros_distro: true
  tasks:
    - name: Setup apt-key for ROS 2
      become: "{{ rose_use_become }}"
      block:
        - name: Add ROS 2 GPG key
          get_url:
            url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
            dest: /usr/share/keyrings/ros-archive-keyring.gpg
        - name: Get dpkg architecture
          register: dpkg_architecture
          changed_when: false
          command: dpkg --print-architecture
        - name: Add ROS 2 apt source
          apt_repository:
            repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main"
            filename: ros2
        - name: Update apt cache
          apt:
            update_cache: true
    - name: Install ros-base packages
      become: "{{ rose_use_become }}"
      apt:
        install_recommends: false
        name:
          - ros-{{ rose_effective_ros_distro }}-ros-base
